### ISSUE TITLE
No file eventDispatcher/init.lua when starting any programs downloaded with the init?

### ISSUE THREAD

**Issue by trentonyo** [InfinitiesLoop/oclib#5]
I've never used a program downloaded on OC so forgive me if I missed some groundwork. I used the tutorial for install outlined in the thread linked in the README, and then followed it up with the guide submitted recently by another contributor - I have all the files installed (or so I thought) but when I try to run builder it can't find "~/eventDispatcher/init.lua" in any directories (it tries to search usr/lib home/lib and my path where everything is installed c/oclib

Any help would be great, I don't know how to copy the errorlog

**Comment by Equalitymind** [comment]
I had the same mistake. There seems to be an error in the installation file. I have copied the following files into another folder since then it works:

Oclib main folder: 

eventDispatcher.lua -> /lib/
smartmove.lua -> /lib/
util.lua -> /lib/
serializer.lua -> /lib/
inventory.lua -> /lib/
autolevel.lua -> /lib/
cleanup.lua -> /lib/
obejectStore -> /lib/

/oclib/builder/ folder:

model.lua -> /lib/builder/
pathing.lua -> /lib/builder/
shapes.lua -> /lib/builder/

Good luck
